[mgr]

show_hidden   = true
show_symlink  = true

[preview]

tab_size      = 2


[opener]
edit          = [
  { run = 'nvim "$@"', block = true, for = "unix" }
]
open          = [
  { run = 'zathura "$@"', block = true, for = "unix" }
]

[open]
prepend_rules = [
  { name = "*.pdf", use = "open" }
]

